name: Build
on:
  pull_request:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: '25.3'
          elixir-version: '1.14.5'
      - run: mix deps.get
      - run: mix format --check-formatted
        env:
          MIX_ENV: test

  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['25.3']
        elixir: ['1.14.5']
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
